server:
  servlet:
    context-path: /${spring.application.name}
  ssl:
    key-store: /usr/local/microservices/zevrant-home-services/zevrant-home-ui/zevrant-services.p12
    key-store-type: PKCS12
    key-store-password: ${password}

zuul:
  routes:
    model:
      sensitiveHeaders:
      path: /zevrant-model-service/**
      url: https://zevrant-model-service
      stripPrefix: false
    oauth:
      sensitiveHeaders:
      path: /zevrant-oauth2-service/**
      url: https://zevrant-oauth2-service
      stripPrefix: false
    outsource:
      sensitiveHeaders:
      path: /zevrant-outsource-service/**
      url: https://zevrant-outsource-service
      stripPrefix: false
    dnd:
      sensitiveHeaders:
      path: /zevrant-dnd-service/**
      url: https://zevrant-dnd-service
      stripPrefix: false
  ssl-hostname-validation-enabled: false
